### ISSUE TITLE
Command for Setup Account and Client

### ISSUE THREAD

**Issue by renanpalmeira** [renanpalmeira/django-panel#2]
Write a command in Django for setup first Account and Client (project).
For example:

Name of project: 
Site of project: 
E-Mail: 
Username: 
Password:

**Comment by RenanPalmeira** [comment]
Add in command a function 'call_command' for started migrate's and loaddata's

**Comment by Wellington475** [comment]
Put "compilemessage" in call_command, because it does not compile the files.po
